version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:alpine-jdk17
    restart: unless-stopped
    privileged: true
    user: root
    networks:
      - compose-net
    ports:
            #- 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    networks:
      - compose-net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/nginx:/etc/nginx
        #      - /etc/letsencrypt:/etc/letsencrypt
        #      - /var/lib/letsencrypt:/var/lib/letsencrypt
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    command: "certonly --standalone --email $EMAIL --agree-tos --preferred-challenges http -d $DOMAIN"
    networks:
      - compose-net
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    depends_on:
      - nginx
networks:
  compose-net:
    name: compose-net
